# Site settings
title: Humane Tech Oracle Deck
email: egrumbac@gmail.com
description: a project of the lincoln center for applied ethics at arizona state university
baseurl: /ht_oracle
url: https://egrumbac.github.io/

twitter_username:
github_username:

# Build settings
markdown: kramdown
